version: "3"
services:
  infra:
    container_name: infra
    build:
      context: ./
      dockerfile: ./infra/Dockerfile
    volumes:
      - ./infra/terraform:/apps/terraform
      - ./infra/terragrunt.hcl:/apps/terragrunt.hcl
      - ./.aws-credentials:/root/.aws/credentials
